# Generated by Django 2.0.5 on 2018-06-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configs',
            name='funcao_transferencia',
            field=models.CharField(choices=[('SG', 'Sigmóide'), ('TH', 'Tangente Hiperbólica')], default='SG', max_length=1),
        ),
        migrations.AlterField(
            model_name='configs',
            name='intervalo',
            field=models.CharField(choices=[('1', '[0, 1]'), ('2', '[-1, 0]'), ('3', '[-1, 1]'), ('4', '[-0.1, 0.1]')], default='1', max_length=1),
        ),
    ]
