# Generated by Django 2.0.5 on 2018-06-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180611_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='rna',
            name='epoca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='erro',
            name='rna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RNA'),
        ),
    ]
