# Generated by Django 2.0.5 on 2018-06-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180611_0256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configs',
        ),
        migrations.RemoveField(
            model_name='rna',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rna',
            name='price',
        ),
        migrations.AddField(
            model_name='rna',
            name='bias',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rna',
            name='funcao_transferencia',
            field=models.CharField(choices=[('SG', 'Sigmóide'), ('TH', 'Tangente Hiperbólica')], default='SG', max_length=1),
        ),
        migrations.AddField(
            model_name='rna',
            name='intervalo',
            field=models.CharField(choices=[('1', '[0, 1]'), ('2', '[-1, 0]'), ('3', '[-1, 1]'), ('4', '[-0.1, 0.1]')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='rna',
            name='momento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='erro',
            name='valor',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
