# Generated by Django 2.0.5 on 2018-06-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180611_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neuronio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='rna',
            name='intervalo',
            field=models.CharField(choices=[('1', '(0, 1)'), ('2', '(-1, 0)'), ('3', '(-1, 1)'), ('4', '(-0.1, 0.1)')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='neuronio',
            name='rna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.RNA'),
        ),
    ]
