# Generated by Django 2.0.5 on 2018-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180611_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuronio',
            name='tipo',
            field=models.CharField(choices=[('I', 'Entrada'), ('H', 'Hidden'), ('O', 'Saída')], default='I', max_length=1),
        ),
    ]
