# Generated by Django 2.0.5 on 2018-06-11 12:39

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_neuronio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erro',
            name='valor',
        ),
        migrations.AddField(
            model_name='erro',
            name='valores',
            field=jsonfield.fields.JSONField(default='None'),
            preserve_default=False,
        ),
    ]
