# Generated by Django 2.0.5 on 2018-06-11 14:36

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180611_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rna',
            name='momento',
        ),
        migrations.AddField(
            model_name='erro',
            name='absolutos',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rna',
            name='funcao_transferencia',
            field=models.CharField(choices=[('SG', 'Sigmóide'), ('EL', 'ELU'), ('RL', 'ReLU'), ('TH', 'Tangente Hiperbólica')], default='SG', max_length=1),
        ),
    ]
