# Generated by Django 2.0.5 on 2018-06-11 15:00

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180611_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='rna',
            name='peso1',
            field=jsonfield.fields.JSONField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rna',
            name='peso2',
            field=jsonfield.fields.JSONField(default='None'),
            preserve_default=False,
        ),
    ]
